### ISSUE TITLE
Composition crash

### ISSUE THREAD

**Issue by Shabinder** [dokar3/compose-sonner#83]
```
Fatal Exception: xw: Compose Runtime internal error. Unexpected or incorrect use of the Compose internal runtime API (pending composition has not been applied). Please report to Google or use https://goo.gle/compose-feedback
       at androidx.compose.runtime.ComposerKt.composeRuntimeError(Composer.kt:11)
       at androidx.compose.runtime.CompositionImpl.drainPendingModificationsForCompositionLocked(Composition.kt:67)
       at androidx.compose.runtime.CompositionImpl.m(Composition.kt:4)
       at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:51)
      .
      .
>        at com.dokar.sonner.Platform_androidKt$ToasterPopup$1.invoke$lambda$3(Platform_android.kt:326)

       at androidx.compose.ui.input.pointer.PointerInteropFilter$pointerInputFilter$1$onCancel$1.invoke(PointerInteropFilter.java:21)
       at androidx.compose.ui.input.pointer.PointerInteropFilter$pointerInputFilter$1$onCancel$1.invoke(PointerInteropFilter.java:21)
       at androidx.compose.ui.input.pointer.PointerInteropUtils_androidKt.emptyCancelMotionEventScope(PointerInteropUtils_android.kt:3
      .
      .        
```

**Comment by orelvis15** [comment]
Same error here!!!
